import type { Movie } from "./types";

export const SEED_MOVIES: Movie[] = [
  {
    id: "swapped",
    title: "Swapped",
    description:
      "One mistake... and everything changed. A gripping Nigerian drama filled with suspense, conflict, and shocking revelations starring Maurice Sam and Chinenye Nnebe.",
    genre: ["Drama"],
    year: 2026,
    rating: 8.0,
    duration: 130,
    thumbnailUrl: "https://i.ibb.co/mrtkbX5c/swapped-movie-thumbnail.jpg",
    accent: "#e11d2e",
    videoUrl: "https://stream.mux.com/Y4ANziekvHvOMFkLwx161hGFhcCCx9EU5tvWhq1JsZw",
    trailerUrl: "https://www.youtube.com/embed/i-Dd_zjzRcs",
    views: 0,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "she-knows-my-secret",
    title: "She Knows My Secret",
    description:
      "She Knows My Secret is a gripping emotional drama centered around a man who appears to have the perfect life on the outside, but hides a dark secret that could destroy everything he has built.",
    genre: ["Drama", "Romance", "Thriller"],
    year: 2026,
    rating: 8.0,
    duration: 101,
    thumbnailUrl: "https://i.ibb.co/QttKfRn/photo-2026-05-23-23-02-44.jpg",
    accent: "#e11d2e",
    videoUrl: "https://stream.mux.com/PxTR6J2772jiwyJqAAZGdrX637q7CEUXS0068Lr4UeQM",
    trailerUrl: "https://www.youtube.com/embed/f2r_q99S8I0",
    views: 0,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "bitter-sweet",
    title: "Bitter Sweet",
    description:
      "Set in the charming world of a bustling cake shop, Bitter Sweet follows a talented young baker whose simple life takes an unexpected turn when love, ambition, and rivalry collide. A heartwarming yet tense Nigerian romantic drama about the sweet dreams and bitter truths that come with chasing love.",
    genre: ["Drama", "Romance"],
    year: 2026,
    rating: 7.5,
    duration: 90,
    thumbnailUrl: "https://i.ibb.co/whVJcdhD/photo-2026-05-27-09-13-22.jpg",
    accent: "#e11d2e",
    videoUrl: "https://stream.mux.com/02Cis6JijDhIsVxkdcM21QZNf1Sgu02YoPKCb00A019oNWY",
    trailerUrl: "https://www.youtube.com/embed/NfH7_Lxe8Ik",
    views: 0,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "me-over-us",
    title: "Me Over Us",
    description:
      "When ambition takes the lead, love falls behind. Me Over Us is a compelling Nigerian drama about a career-driven woman torn between her relentless pursuit of success and the relationship she risks losing along the way. A powerful story of love, sacrifice, and the price of putting yourself first.",
    genre: ["Drama", "Romance"],
    year: 2026,
    rating: 8.0,
    duration: 110,
    thumbnailUrl: "https://i.ibb.co/YT0FMsCW/photo-2026-05-23-12-53-40.jpg",
    accent: "#e11d2e",
    videoUrl: "https://stream.mux.com/lTbrPWVFz6EceuYTB6p15k7du11uL902Jqzx92HHhBeM",
    trailerUrl: "https://www.youtube.com/embed/L8FpBvW_W_0",
    views: 0,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "jato-the-general",
    title: "Jato The General",
    description:
      "Jato The General is an entertaining Nigerian comedy-drama following the larger-than-life antics of a self-proclaimed 'general' whose schemes, charm, and bold ambitions stir up chaos and laughter. Packed with drama, humor, and unexpected twists, starring Nosa Rex, Queen Enechi, and Mercy Chinedu.",
    genre: ["Comedy", "Drama"],
    year: 2026,
    rating: 8.0,
    duration: 108,
    thumbnailUrl: "https://i.ibb.co/RkJBj775/photo-2026-05-17-17-18-48.jpg",
    accent: "#e11d2e",
    videoUrl: "https://stream.mux.com/M6f003iYm46PughwLONu5bTM5bjq00SE3ytq60027RAYAk",
    trailerUrl: "https://www.youtube.com/embed/6T1A8-Nq7AI",
    views: 0,
    featured: true,
    createdAt: new Date().toISOString(),
  },
];